-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 17:18:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`indirizzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`indirizzo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paese` VARCHAR(45) NOT NULL,
  `citta` VARCHAR(45) NOT NULL,
  `via` VARCHAR(45) NOT NULL,
  `numero_civico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `data_nascita` DATE NOT NULL,
  `numero_telefono` INT NULL,
  `indirizzo_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_utente_indirizzo_idx` (`indirizzo_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `numero_telefono_UNIQUE` (`numero_telefono` ASC) VISIBLE,
  CONSTRAINT `fk_utente_indirizzo`
    FOREIGN KEY (`indirizzo_id`)
    REFERENCES `mydb`.`indirizzo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linguaggio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`linguaggio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`capitolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`capitolo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_capitolo` INT NOT NULL,
  `argomento` VARCHAR(500) NOT NULL,
  `linguaggio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_capitolo_linguaggio1_idx` (`linguaggio_id` ASC) VISIBLE,
  CONSTRAINT `fk_capitolo_linguaggio1`
    FOREIGN KEY (`linguaggio_id`)
    REFERENCES `mydb`.`linguaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quiz_vero_falso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quiz_vero_falso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `domanda` VARCHAR(100) NOT NULL,
  `bool` TINYINT NOT NULL,
  `linguaggio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quiz_linguaggio1_idx` (`linguaggio_id` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_linguaggio1`
    FOREIGN KEY (`linguaggio_id`)
    REFERENCES `mydb`.`linguaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quiz_multiplo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quiz_multiplo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `domanda` VARCHAR(100) NOT NULL,
  `corretta` VARCHAR(100) NOT NULL,
  `errore1` VARCHAR(100) NOT NULL,
  `errore2` VARCHAR(100) NOT NULL,
  `linguaggio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quiz_multiplo_linguaggio1_idx` (`linguaggio_id` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_multiplo_linguaggio1`
    FOREIGN KEY (`linguaggio_id`)
    REFERENCES `mydb`.`linguaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`badge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utente_has_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utente_has_badge` (
  `utente_id` INT NOT NULL,
  `badge_id` INT NOT NULL,
  `conseguimento_badge` DATE NULL,
  PRIMARY KEY (`utente_id`, `badge_id`),
  INDEX `fk_utente_has_badge_badge1_idx` (`badge_id` ASC) VISIBLE,
  INDEX `fk_utente_has_badge_utente1_idx` (`utente_id` ASC) VISIBLE,
  CONSTRAINT `fk_utente_has_badge_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `mydb`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utente_has_badge_badge1`
    FOREIGN KEY (`badge_id`)
    REFERENCES `mydb`.`badge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
